import Link from 'next/link'
import { ArrowLeft, ArrowRight, Check, CircleDot } from 'lucide-react'
import { resources } from '@/lib/resources'
import { getCurrency, getPrice } from '@/lib/commerce'
import { CheckoutButton } from '@/components/checkout-button'

export function generateStaticParams() { return resources.map((resource) => ({ slug: resource.slug })) }

export default async function ResourcePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const resource = resources.find((item) => item.slug === slug) ?? resources[0]
  const price = getPrice(resource)
  const currency = getCurrency()
  return <main className="site-shell detail-page"><header className="topbar"><Link href="/" className="brand"><span>STANISLAV ILIEV</span><strong>WORKFLOWS <i>&amp;</i> AUTOMATIONS</strong></Link><Link href="/" className="back-link"><ArrowLeft /> Back to resources</Link></header><section className="detail-hero section-pad"><div className="section-kicker"><span>{resource.number}</span><span>{resource.badge}</span></div><h1>{resource.title}</h1><p>{resource.description}</p><div className="detail-meta"><span>PRICE</span><strong>{resource.slug === 'ai-bug-bounty-playbook' ? '149 EUR' : price ? price + ' ' + currency : 'Цена — очаквайте скоро'}</strong>{resource.slug === 'ai-bug-bounty-playbook' ? <a className="button primary checkout-submit" href="https://mypos.com/vmp/btn/BMFVSS4N9BP85" target="_blank" rel="noopener noreferrer">КУПИ ЗА €149 <ArrowRight /></a> : <CheckoutButton slug={resource.slug} amount={price} currency={currency} />}</div></section><section className="detail-content section-pad"><div className="detail-column"><div className="section-kicker"><span>01</span><span>WHAT YOU GET</span></div><h2>Структурирана база за следващата ти <em>стъпка.</em></h2><p>След потвърдено плащане получавате оригиналния PDF продукт и фактурния документ автоматично на посочения имейл.</p><div className="check-list"><span><Check /> Достъп до дигиталния ресурс</span><span><Check /> PDF доставка по имейл</span><span><Check /> Фактурен документ</span></div></div><div className="module-panel"><span className="panel-label">RESOURCE / MODULES</span>{['STRUCTURED KNOWLEDGE','PRACTICAL WORKFLOW','NEXT ACTION'].map((item, i) => <div className="module-row" key={item}><span>0{i + 1}</span><strong>{item}</strong><CircleDot /></div>)}<p>Доставката се активира след server-side потвърждение от myPOS.</p></div></section><section className="detail-workflow section-pad"><div className="section-kicker"><span>02</span><span>WORKFLOW</span></div><h2>Resource <em>→</em> Action</h2><div className="detail-flow"><span>RESOURCE</span><ArrowRight /><span>KNOWLEDGE</span><ArrowRight /><span>WORKFLOW</span><ArrowRight /><span>ACTION</span></div><div className="audience"><span>WHO IS IT FOR</span><p>За хора и компании, които искат да откриват възможности, да автоматизират процеси и да изграждат по-ефективен онлайн бизнес.</p></div></section><footer className="footer section-pad"><div className="footer-brand"><span>STANISLAV ILIEV</span><strong>WORKFLOWS &amp; AUTOMATIONS</strong></div><div className="footer-bottom"><span>© 2026 STANISLAV ILIEV</span><Link href="/">Back to home</Link></div></footer></main>
}
